name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$REPO_SECURE" == "repo" ]
          then
            echo "Got secret"
          fi
          if [ "$ORG_SECURE" == "org" ]
          then
            echo "Got secret something else"
          fi
        env: 
          REPO_SECURE: ${{ secrets.REPO_SECRETS }}
          ORG_SECURE: ${{ secrets.ORGANIZATION_SECRETS }}
          
