name: Secrets example
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          if [ "$REPO_SECURE" == "repo" ]
          then
            echo "Got secret"
        env: 
          REPO_SECURE: ${{ secrets.REPO_SECRETS }}
          
